-- MySQL Script generated by MySQL Workbench
-- seg 02 set 2019 10:09:20 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `idaluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `nota1` FLOAT NOT NULL,
  `nota2` FLOAT NOT NULL,
  `media` FLOAT NULL,
  `idnota` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idnota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `iddisciplina` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cargahoraria` INT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idcurso` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dependente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `idprofessor` INT NOT NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`id`, `idprofessor`),
  INDEX `fk_dependente_professor1_idx` (`idprofessor` ASC),
  CONSTRAINT `fk_dependente_professor1`
    FOREIGN KEY (`idprofessor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diario` (
  `iddiario` INT NOT NULL,
  `idnota` INT NULL,
  `idaluno` INT NULL,
  PRIMARY KEY (`iddiario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `unidade` VARCHAR(10) NOT NULL,
  `data_avaliacao` DATETIME NOT NULL,
  `nota_maxima` DECIMAL(4,2) NOT NULL,
  `nota_minima` DECIMAL(4,2) NOT NULL,
  `peso` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`idavaliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diario_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diario_professor` (
  `diario_iddiario` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  `funcao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`diario_iddiario`, `professor_idprofessor`),
  INDEX `fk_diario_has_professor_professor2_idx` (`professor_idprofessor` ASC),
  INDEX `fk_diario_has_professor_diario1_idx` (`diario_iddiario` ASC),
  CONSTRAINT `fk_diario_has_professor_diario1`
    FOREIGN KEY (`diario_iddiario`)
    REFERENCES `mydb`.`diario` (`iddiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_has_professor_professor2`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacao_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacao_diario` (
  `avaliacao_idavaliacao` INT NOT NULL,
  `iddiario` INT NOT NULL,
  PRIMARY KEY (`avaliacao_idavaliacao`, `iddiario`),
  INDEX `fk_avaliacao_has_diario_diario1_idx` (`iddiario` ASC),
  INDEX `fk_avaliacao_has_diario_avaliacao1_idx` (`avaliacao_idavaliacao` ASC),
  CONSTRAINT `fk_avaliacao_has_diario_avaliacao1`
    FOREIGN KEY (`avaliacao_idavaliacao`)
    REFERENCES `mydb`.`avaliacao` (`idavaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_has_diario_diario1`
    FOREIGN KEY (`iddiario`)
    REFERENCES `mydb`.`diario` (`iddiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diario_curso` (
  `diario_iddiario` INT NOT NULL,
  `curso_idcurso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`diario_iddiario`, `curso_idcurso`),
  INDEX `fk_diario_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_diario_has_curso_diario1_idx` (`diario_iddiario` ASC),
  CONSTRAINT `fk_diario_has_curso_diario1`
    FOREIGN KEY (`diario_iddiario`)
    REFERENCES `mydb`.`diario` (`iddiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina_diario` (
  `disciplina_iddisciplina` INT UNSIGNED NOT NULL,
  `diario_iddiario` INT NOT NULL,
  PRIMARY KEY (`disciplina_iddisciplina`, `diario_iddiario`),
  INDEX `fk_disciplina_has_diario_diario1_idx` (`diario_iddiario` ASC),
  INDEX `fk_disciplina_has_diario_disciplina1_idx` (`disciplina_iddisciplina` ASC),
  CONSTRAINT `fk_disciplina_has_diario_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `mydb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_has_diario_diario1`
    FOREIGN KEY (`diario_iddiario`)
    REFERENCES `mydb`.`diario` (`iddiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diario_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diario_professor` (
  `diario_iddiario` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  `funcao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`diario_iddiario`, `professor_idprofessor`),
  INDEX `fk_diario_has_professor_professor2_idx` (`professor_idprofessor` ASC),
  INDEX `fk_diario_has_professor_diario1_idx` (`diario_iddiario` ASC),
  CONSTRAINT `fk_diario_has_professor_diario1`
    FOREIGN KEY (`diario_iddiario`)
    REFERENCES `mydb`.`diario` (`iddiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diario_has_professor_professor2`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_avaliacao` (
  `aluno_idaluno` INT UNSIGNED NOT NULL,
  `avaliacao_idavaliacao` INT NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `avaliacao_idavaliacao`),
  INDEX `fk_aluno_has_avaliacao_avaliacao1_idx` (`avaliacao_idavaliacao` ASC),
  INDEX `fk_aluno_has_avaliacao_aluno1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_aluno_has_avaliacao_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `mydb`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_avaliacao_avaliacao1`
    FOREIGN KEY (`avaliacao_idavaliacao`)
    REFERENCES `mydb`.`avaliacao` (`idavaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota_avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota_avaliacao` (
  `nota_idnota` INT UNSIGNED NOT NULL,
  `idavaliacao` INT NOT NULL,
  `somatorio_notas` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`nota_idnota`, `idavaliacao`),
  INDEX `fk_nota_has_avaliacao_avaliacao1_idx` (`idavaliacao` ASC),
  INDEX `fk_nota_has_avaliacao_nota1_idx` (`nota_idnota` ASC),
  CONSTRAINT `fk_nota_has_avaliacao_nota1`
    FOREIGN KEY (`nota_idnota`)
    REFERENCES `mydb`.`nota` (`idnota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_has_avaliacao_avaliacao1`
    FOREIGN KEY (`idavaliacao`)
    REFERENCES `mydb`.`avaliacao` (`idavaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
