-- MySQL Script generated by MySQL Workbench
-- qua 29 mai 2019 21:20:11 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `idaluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `nota1` FLOAT NOT NULL,
  `nota2` FLOAT NOT NULL,
  `media` FLOAT NULL,
  `idnota` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idnota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idcurso` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NULL,
  `curso_idcurso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idprofessor`),
  INDEX `fk_professor_curso_idx` (`curso_idcurso` ASC),
  CONSTRAINT `fk_professor_curso`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `iddisciplina` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cargahoraria` INT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ministra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ministra` (
  `professor_idprofessor` INT NOT NULL,
  `aluno_idaluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`professor_idprofessor`, `aluno_idaluno`),
  INDEX `fk_professor_has_aluno_aluno1_idx` (`aluno_idaluno` ASC),
  INDEX `fk_professor_has_aluno_professor1_idx` (`professor_idprofessor` ASC),
  CONSTRAINT `fk_professor_has_aluno_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_has_aluno_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `mydb`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordena` (
  `disciplina_iddisciplina` INT UNSIGNED NOT NULL,
  `curso_idcurso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`disciplina_iddisciplina`, `curso_idcurso`),
  INDEX `fk_disciplina_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_disciplina_has_curso_disciplina1_idx` (`disciplina_iddisciplina` ASC),
  CONSTRAINT `fk_disciplina_has_curso_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `mydb`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disciplina_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
